[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = [
  "npm ci",
  "cd backend && npm ci",
  "cd ../frontend && npm ci"
]

[phases.build]
cmds = [
  "cd backend && npm run build",
  "cd ../frontend && npm run build"
]

[start]
cmd = "cd backend && npm start"
