[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = [
  "npm ci && chmod +x node_modules/.bin/*",
  "cd /app/backend && npm ci && chmod +x node_modules/.bin/*",
  "cd /app/frontend && npm ci && chmod +x node_modules/.bin/*"
]

[phases.build]
cmds = [
  "cd /app/backend && npm run build",
  "cd /app/frontend && npm run build"
]

[start]
cmd = "cd /app/backend && npm start"
